#!/usr/bin/env python3
"""Seed demo data for PROJECT_HIRE_DESK_AI.

Posts a handful of realistic (but fictional) job applications to the deployed
API so the Kanban board and dashboard have something to show during a demo.

Usage (PowerShell):
    $env:API_BASE_URL = "https://<your-api-id>.execute-api.<region>.amazonaws.com"
    python scripts/seed_demo_data.py

The script:
  - reads the API base URL from the API_BASE_URL environment variable;
  - POSTs each sample application to <base>/applications;
  - prints one concise line per application;
  - continues on per-request failures;
  - exits 0 only when every application succeeds, non-zero otherwise.

Standard library only. No third-party dependencies. POST only (never deletes).
"""

import json
import os
import sys
import urllib.error
import urllib.request

# ---------------------------------------------------------------------------
# Sample applications
# ---------------------------------------------------------------------------
# Payload shape matches the real POST /applications contract enforced by
# backend/applications_function/validators/payload_validator.py and
# backend/applications_function/services/applications_service.py:
#   - jobTitle:        required, non-empty string
#   - company:         optional string
#   - location:        optional string
#   - skills:          list[str]
#   - responsibilities:list[str]
#   - languages:       list[str]
#   - experienceLevel: optional string
#   - status:          one of Wishlist | Applied | Interview | Offer | Rejected
# Server-side fields (userId, applicationId, timestamps, statusHistory,
# nextAction) are generated by the backend and must NOT be supplied here.
SAMPLE_APPLICATIONS = [
    {
        "jobTitle": "Senior Frontend Engineer",
        "company": "Northwind Labs",
        "location": "Remote (EU)",
        "skills": ["Vue 3", "TypeScript", "Vite", "Pinia", "CSS"],
        "responsibilities": [
            "Build and maintain the component library",
            "Collaborate with designers on the design system",
            "Improve web performance and accessibility",
        ],
        "languages": ["English", "French"],
        "experienceLevel": "Senior",
        "status": "Applied",
    },
    {
        "jobTitle": "Backend Developer (Python)",
        "company": "Cobalt Systems",
        "location": "Lisbon, Portugal",
        "skills": ["Python", "AWS Lambda", "DynamoDB", "API Gateway"],
        "responsibilities": [
            "Design serverless REST APIs",
            "Write unit and property-based tests",
            "Own service reliability and observability",
        ],
        "languages": ["English", "Portuguese"],
        "experienceLevel": "Mid",
        "status": "Interview",
    },
    {
        "jobTitle": "Cloud Solutions Architect",
        "company": "Meridian Cloud",
        "location": "Dublin, Ireland",
        "skills": ["AWS", "Infrastructure as Code", "SAM", "CloudFormation"],
        "responsibilities": [
            "Define reference architectures for customers",
            "Lead cloud migration engagements",
            "Mentor engineering teams on best practices",
        ],
        "languages": ["English"],
        "experienceLevel": "Senior",
        "status": "Wishlist",
    },
    {
        "jobTitle": "Full Stack Engineer",
        "company": "BrightWave",
        "location": "Berlin, Germany",
        "skills": ["Vue", "Node.js", "PostgreSQL", "Docker"],
        "responsibilities": [
            "Deliver features across frontend and backend",
            "Participate in code reviews",
            "Contribute to CI/CD pipelines",
        ],
        "languages": ["English", "German"],
        "experienceLevel": "Mid",
        "status": "Offer",
    },
    {
        "jobTitle": "Junior Software Developer",
        "company": "Pinecrest Digital",
        "location": "Paris, France",
        "skills": ["JavaScript", "HTML", "CSS", "Git"],
        "responsibilities": [
            "Assist in building web features",
            "Fix bugs and write tests",
            "Learn from senior engineers",
        ],
        "languages": ["French", "English"],
        "experienceLevel": "Junior",
        "status": "Rejected",
    },
    {
        "jobTitle": "DevOps Engineer",
        "company": "Aurora Analytics",
        "location": "Amsterdam, Netherlands",
        "skills": ["AWS", "Terraform", "CI/CD", "Monitoring", "Python"],
        "responsibilities": [
            "Automate deployments and infrastructure",
            "Improve observability and alerting",
            "Reduce operational toil",
        ],
        "languages": ["English", "Dutch"],
        "experienceLevel": "Senior",
        "status": "Applied",
    },
    {
        "jobTitle": "Product Designer",
        "company": "Lumen Studio",
        "location": "Barcelona, Spain",
        "skills": ["Figma", "User Research", "Prototyping", "Design Systems"],
        "responsibilities": [
            "Design end-to-end user flows",
            "Run usability tests",
            "Partner with engineers on delivery",
        ],
        "languages": ["English", "Spanish"],
        "experienceLevel": "Mid",
        "status": "Wishlist",
    },
]


def _get_base_url() -> str:
    """Return the normalized API base URL or exit with a clear error."""
    base_url = os.environ.get("API_BASE_URL", "").strip()
    if not base_url:
        print(
            "ERROR: API_BASE_URL environment variable is not set or empty.\n"
            "       Set it to the deployed API base URL and retry, e.g.:\n"
            '       PowerShell:  $env:API_BASE_URL = '
            '"https://<api-id>.execute-api.<region>.amazonaws.com"',
            file=sys.stderr,
        )
        sys.exit(2)
    # Normalize: strip trailing slashes so "<base>" and "<base>/" behave alike.
    return base_url.rstrip("/")


def _post_application(endpoint: str, payload: dict) -> tuple[bool, str]:
    """POST a single application. Return (success, detail)."""
    body = json.dumps(payload).encode("utf-8")
    request = urllib.request.Request(
        endpoint,
        data=body,
        method="POST",
        headers={"Content-Type": "application/json"},
    )
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            status_code = response.getcode()
            if 200 <= status_code < 300:
                return True, f"HTTP {status_code}"
            return False, f"HTTP {status_code}"
    except urllib.error.HTTPError as exc:
        return False, f"HTTP {exc.code}"
    except urllib.error.URLError as exc:
        return False, f"connection error: {exc.reason}"
    except Exception as exc:  # noqa: BLE001 - keep seeding the rest
        return False, f"unexpected error: {type(exc).__name__}"


def main() -> int:
    base_url = _get_base_url()
    endpoint = f"{base_url}/applications"

    total = len(SAMPLE_APPLICATIONS)
    failures = 0

    print(f"Seeding {total} demo applications -> {endpoint}")

    for app in SAMPLE_APPLICATIONS:
        status = app.get("status", "Wishlist")
        job_title = app.get("jobTitle", "(untitled)")
        company = app.get("company", "(no company)")
        label = f"[{status}] {job_title} @ {company}"

        ok, detail = _post_application(endpoint, app)
        if ok:
            print(f"OK   {label}")
        else:
            failures += 1
            print(f"FAIL {label} -> {detail}")

    succeeded = total - failures
    print(f"\nDone: {succeeded}/{total} applications created, {failures} failed.")

    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
